[[news]]
date = "ğŸ®"
content = "Game: Living and travelling in magical worlds."

[[news]]
date = "ğŸ“"
content = "Ping Pang: A forgetten skill."

[[news]]
date = "ğŸµ"
content = "Music: Singing songs everyday."
