type = "card"
title = "Recent Works"
description = "Latest projects and achievements."

[[items]]
title = "Ultra-Low Power WURX for HUAWEI-SLZ"
subtitle = "2025"
content = "Designed a 30uw ultra low power WURX for HUAWEI-SparkLink-Zeropower."

[[items]]
title = "Ultra-Wideband Specturm Sensing system For CSG"
subtitle = "2026"
content = "Trying to design an ultra-wideband specturm sensing system that monitors the range from 0.2 GHz to 6 GHz."
